version: '3.8'

services:
  motor-db:
    image: postgres:16
    container_name: motor-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: motor_social_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d # <--- Esto carga tu volcado en AWS

  motor-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: motor-app
    restart: always
    ports:
      - "80:3000" # El puerto web normal apunta a tu backend
    env_file:
      - .env
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - motor-db