version: '3.8'

services:
  # SERVICIO 1: La Base de Datos
  motor-db:
    image: postgres:16
    container_name: motor-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: motor_social_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # SERVICIO 2: Panel de gestión web
  pgadmin:
    image: dpage/pgadmin4
    container_name: motor-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@motor.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - motor-db

  # SERVICIO 3: Backend
  motor-app:
    build: ./backend
    container_name: motor-app
    restart: always  # Añade esto para que si falla, reviva solo
    ports:
      - "3000:3000"
    # Quitamos el volume de /app para que use el código de la imagen (más estable)
    env_file:
      - ./backend/.env # Asegúrate de que el .env esté dentro de la carpeta backend
    depends_on:
      - motor-db

  # SERVICIO 4: Frontend
  motor-front:
    build: ./frontend
    container_name: motor-front
    restart: always
    ports:
      - "5173:5173"
    # IMPORTANTE: Quitamos la sección 'environment' para que NO pise al 'env_file'
    env_file:
      - ./frontend/.env
    # El comando debe ser este para que Vite acepte conexiones externas
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - motor-app